name: anuncios_colaboradores
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.12
  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/exercicio/

